# Generated by Django 4.1.3 on 2022-11-26 02:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeVisitingAllAttractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visit_all_attractions', models.BooleanField(default=False)),
                ('time', models.IntegerField(default=-1)),
                ('date', models.DateField()),
                ('route', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
