# Generated by Django 4.1.3 on 2022-12-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disneyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeVisitingAllAttractions',
            new_name='WadaAlgorithm',
        ),
    ]
